### ISSUE TITLE
[BUG/ECHO-SERVER] The default HTTP header syntax "HTTP_CODE" is invalid.

### ISSUE THREAD

**Issue by epourail** [Ealenn/charts#29]
**Describe the bug**
The default chart configuration is invalid on the `livenessProbe.httpGet.httpHeaders[0].name` value.
The default HTTP header syntax `HTTP_CODE` is invalid.

**To Reproduce**
1. On a local kubernetes cluster like `kind`
2. Install the echo-server chart with the default values : `helm upgrade -i echo ealenn/echo-server --namespace my_namespace --force`
3. The deployment failed with the error `... Invalid value: "ECHO_CODE": a valid HTTP header must consist of alphanumeric characters or '-' (e.g. 'X-Header-Name', regex used for validation is '[-A-Za-z0-9]+')` 

**Expected behavior**
Deployment suceeded without error
Note : to avoid the issue, I must define the deployment values : 
```
livenessProbe:
  httpGet:
    httpHeaders: ~
```
**Desktop (please complete the following information):**
 - OS: Linux
 - Version : Ubuntu 18.04

**Additional context**
 - Kind v0.6.0

**Comment by Ealenn** [comment]
Resolved in [0.4.0](https://github.com/Ealenn/Echo-Server/releases/tag/0.4.0)

**Comment by Ealenn** [comment]
The chart has been updated to version 0.3.0 #30 

It embeds the App in version 0.4.0 :) 
Thanks!
