### ISSUE TITLE
[FEATURE/echo-server] 

### ISSUE THREAD

**Issue by kyounger** [Ealenn/charts#35]
**Is your feature request related to a problem? Please describe.**
Looking to upgrade to 0.5.1

**Describe the solution you'd like**
Needed features in 0.5.0, and temporarily set the image to the new version, but figured a proper upgrade to the chart was also warranted.

**Describe alternatives you've considered**
Just updated the tag version in the current chart

**Additional context**
I was happy to even potentially look at helping with the PR, but noticed you prefer an upfront discussion of that first, so here we are :)

**Comment by Ealenn** [comment]
Ah ah ! Thanks @kyounger ! Great initiative, I must upgrade this chart for a while... If you want make PR is with pleasure 🤙 

Do not forget to modify the documentation (You can put your name on changelog) and increase semver of the chart https://github.com/Ealenn/charts/blob/master/charts/echo-server/Chart.yaml#L3 😁

Normally in Readme you can find all tools to help you.

If you don't have time, I can take care of it on this weekend.
