### ISSUE TITLE
Support networking.k8s.io/v1 for Ingress

### ISSUE THREAD

**Issue by dangarthwaite** [Ealenn/charts#37]
See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

I couldn't wait until Hacktoberfest to submit this patch.  There is a wrinkle in that I can't figure out how to determin if $svcPort is an integer or string.

**Comment by dangarthwaite** [comment]
https://github.com/Ealenn/charts/pull/38

**Comment by Ealenn** [comment]
Thank you, do not hesitate to reopen this ticket in case of problems
